/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        IMPORT MODULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

//general workflow modules 
include { SAMTOOLS_FAIDX      } from '../../../modules/nf-core/samtools/faidx/main.nf'

//modules involved in the generation of a cannonical database
include { STRINGTIE_STRINGTIE } from '../../../modules/nf-core/stringtie/stringtie/main.nf'
include { STRINGTIE_MERGE     } from '../../../modules/nf-core/stringtie/merge/main.nf'
include { GFFCOMPARE          } from '../../../modules/nf-core/gffcompare/main.nf'
include { GFFREAD             } from '../../../modules/nf-core/gffread/main.nf'
include { PYPGATKDNA          } from '../../../modules/local/pypgatk/dnaseq_to_proteindb/main.nf'

//modules involved in the generation of a variant database
include { FREEBAYES            } from '../../../modules/nf-core/freebayes/main.nf'
include { GUNZIP as GUNZIP_VCF } from '../../../modules/nf-core/gunzip/main.nf'
include { BCFTOOLS_INDEX       } from '../../../modules/nf-core/bcftools/index/main.nf'
include { BCFTOOLS_MERGE       } from '../../../modules/nf-core/bcftools/merge/main.nf'
include { PYPGATK_VCF          } from '../../../modules/local/pypgatk/vcf_to_proteindb/main.nf'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        RUN MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

workflow RNASEQDB {

take:

    //inputs from the main workflow
    bam                    //channel: [val(meta), [samplesheet]]
    bai                    //channel: [val(meta), [samplesheet]]
    annotation             //channel: /path/to/genome annotation
    reference              //channel: /path/to/reference genome
    config                 //channel: /path/to/custom config file
    dna_config             //channel: /path/to/dna config file
    cdna                   //channel: /path/to/cdna transcripts
    faidx_get_genome_sizes //boolean: whether FAIDX gets genome sizes
    skip_dnaseq            //boolean: decides whether to skip the cannonical database generation
    skip_vcf               //boolean: decides whether to skip the variant database generation

main:

    //creates empty channels for the final database and versions file
    merged_databases_ch = Channel.empty()
    versions_ch         = Channel.empty()

    //empty channel for the fasta index generated from the genome reference
    fasta_fai_ch        = Channel.empty()

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        START OF THE CANONICAL DATABASE GENERATION PATHWAY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

    //applies a map to the genome annotation
    annotation.map { genome ->
        def meta = [ id: 'Genome' ]
        return [ meta, genome ] }
    .collect()
    .set { annotation_ch}
    

    //applies a map to the genome reference
    reference.map { genome ->
        def meta = [ id: 'genome' ]
        return [ meta, genome ] }
    .collect()
    .set{ reference_ch }
    

    //SAMTOOLS_FAIDX takes the reference genome (fasta) 
    //and generates a fasta index file (fai)
    SAMTOOLS_FAIDX (
        reference_ch,
        [ [], [] ],
        false  
    )
    versions_ch = versions_ch.mix(SAMTOOLS_FAIDX.out.versions_samtools)
    fasta_fai_ch = SAMTOOLS_FAIDX.out.fai.collect()

//conditional execution based on if skip_dnaseq is true or false
if (!skip_dnaseq) {

    //creating empty channels used in the dna database generation pathway
    stringtie_gtf_ch = Channel.empty()
    merged_gtf_ch    = Channel.empty()
    gffcompare_ch    = Channel.empty()
    gffout           = Channel.empty()

    //STRINGTIE is taking the genome annotation and the HISAT2 Bam file 
    //to assemble the RNA-seq alignments into potential transcripts
    STRINGTIE_STRINGTIE (
        bam,
        annotation
    )
    versions_ch = versions_ch.mix(STRINGTIE_STRINGTIE.out.versions_stringtie)
    stringtie_gtf_ch = STRINGTIE_STRINGTIE.out.transcript_gtf
        .map { meta, gtf ->
                return [ gtf ] }
        .collect()

    //stringtie merge is merging the annontation with the potential transcripts generated by STRINGTIE_STRINGTIE
    STRINGTIE_MERGE (
        stringtie_gtf_ch,
        annotation
    )
    versions_ch = versions_ch.mix(STRINGTIE_MERGE.out.versions)
    merged_gtf_ch = STRINGTIE_MERGE.out.gtf
        .map { gtf ->
            def meta = [ id: 'gtf' ]
                return [ meta, gtf ] }
        .collect()

    //cerates an empty channel that will combine the 
    //genome fasta and genome fasta index channels
    fasta_meta_fai_ch = Channel.empty()
    fasta_meta_fai_ch = reference_ch.combine(fasta_fai_ch)
        .map { map1, fasta, map2, fai ->
            def meta = [ id: 'fasta', description: 'Genome FASTA with index' ]
            return [ meta, fasta, fai ] }
        .collect()


    //GFFCOMPARE is taking the genome fasta, genome annotation, and the 
    //output of StringTie to asses the accuracy of the assembly 
    GFFCOMPARE (
        merged_gtf_ch,
        fasta_meta_fai_ch,
        annotation_ch
    )
    versions_ch = versions_ch.mix(GFFCOMPARE.out.versions)
    gffcompare_ch = GFFCOMPARE.out.annotated_gtf.collect()
            .map { meta, gtf_file ->
            def meta1 = [ id: 'gtf_file', single_end:true ]
            return [ meta1, gtf_file ] }

    //GFFREAD takes the GFFCOMPARE output (gtf) and using 
    //the reference genome converts it into transcript sequences
    GFFREAD (
        gffcompare_ch,
        reference
    )
    versions_ch = versions_ch.mix(GFFREAD.out.versions_gffread)
    gffout = GFFREAD.out.gffread_fasta.collect()

    //PYPGATK takes the GFFREAD output (FASTA) and using the dna_config 
    //file generates a database from the fasta transcripts 
    PYPGATKDNA (
        gffout,
        dna_config
    )
    versions_ch = versions_ch.mix(PYPGATKDNA.out.versions)

    //adds the DNA database to the merged_databases_ch
    merged_databases_ch = merged_databases_ch.mix(PYPGATKDNA.out.database).collect()

}

else {
        //bypass the subworkflow
        log.info "rna-seq dna database skipped."
    }
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        END OF THE CANONICAL DATABASE GENERATION PATHWAY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        START OF THE VARIANT DATABASE GENERATION PATHWAY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

//conditional execution based on if skip_vcf is true or false
if (!skip_vcf) {

    //creates empty channels for use in the variant generation pathway
    genome_bam_bai_ch = Channel.empty()
    freebayes_ch      = Channel.empty()
    freebayes_vcf     = Channel.empty()
    vcf_index_ch      = Channel.empty()
    vcf_merge_ch      = Channel.empty()
    vcf_file_ch       = Channel.empty()

    //combines the bam and bam index files into a single channel
    genome_bam_bai_ch = bam.join(bai)
        .map { meta, bam, bai ->
            return [ meta, bam, bai, [], [], [] ] }

    //FREEBAYES takes the bam, bam index, and fasta index files to generate a vcf file 
    FREEBAYES (
        genome_bam_bai_ch,
        reference_ch,
        fasta_fai_ch,
        [ [], [] ],
        [ [], [] ],
        [ [], [] ]
    )
    versions_ch = versions_ch.mix(FREEBAYES.out.versions)
    freebayes_ch = FREEBAYES.out.vcf

    //generates a VCF file index
    BCFTOOLS_INDEX (
        freebayes_ch
    )
    versions_ch = versions_ch.mix(BCFTOOLS_INDEX.out.versions_bcftools)
    vcf_index_ch = BCFTOOLS_INDEX.out.tbi
        .map { meta, index ->
            return index }
        .collect()
        .map { index ->
            def meta2 = [ id: 'key' ]
            return [ meta2, index ] }
  
    freebayes_vcf = freebayes_ch
            .map { meta, vcf ->
                return vcf }
            .collect()
            .map { vcf ->
                def meta2 = [ id: 'key' ]
                return [ meta2, vcf ] }

    vcf_merge_ch = freebayes_vcf.join(vcf_index_ch).collect()

    //merges the VCF files into a single file
    BCFTOOLS_MERGE (
        vcf_merge_ch,
        reference_ch,
        fasta_fai_ch,
        [ [], [] ]
    )
    versions_ch = versions_ch.mix(BCFTOOLS_MERGE.out.versions_bcftools)
    vcf_file_ch = BCFTOOLS_MERGE.out.vcf

    //applies a map to the cdna file
    cdna.map { genome ->
        def meta = [ id: 'cdna' ]
        return [ meta, genome ] }
    .set{ cdna_ch }
    .collect()

    //PYPGATKCUSTOM takes the vcf file generated by FREEBAYES and using cdna 
    //transcripts and the genome annotation it generates a variant peptide database
    PYPGATK_VCF (
        vcf_file_ch,
        annotation_ch,
        cdna_ch,
        config
    )
    versions_ch = versions_ch.mix(PYPGATK_VCF.out.versions)

    //takes the database generated with PYPGATK and combines it with the other database
    merged_databases_ch = merged_databases_ch.mix(PYPGATK_VCF.out.database).collect()

}

else {
    //bypass the subworkflow
    log.info "rna-seq vcf database skipped."
}

/*
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        END OF THE VARIANT DATABASE GENERATION PATHWAY
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

emit:

    //emits to the main workflow
    merged_databases_ch //channel: [ val(meta), [ database ] ]
    versions_ch         //channel: [ path(versions.yml) ]

}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
